-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ff_auditoriums
(
    ff_auditorium          character(26) COLLATE pg_catalog."default"          NOT NULL,
    capacity               smallint                                            NOT NULL,
    name                   character varying(250) COLLATE pg_catalog."default" NOT NULL,
    ff_theater_id          character(26) COLLATE pg_catalog."default"          NOT NULL,
    created_timestamp      timestamp with time zone DEFAULT now(),
    last_updated_timestamp timestamp with time zone DEFAULT now(),
    version_number         integer                  DEFAULT 0,
    created_by             character(26) COLLATE pg_catalog."default",
    last_updated_by        character(26) COLLATE pg_catalog."default",
    CONSTRAINT ff_auditoriums_pkey PRIMARY KEY (ff_auditorium)
);

CREATE TABLE IF NOT EXISTS public.ff_fb_platform_movies
(
    ff_movie_id             character(26) COLLATE pg_catalog."default"          NOT NULL,
    ff_fb_platform_id       character(26) COLLATE pg_catalog."default"          NOT NULL,
    movie_id                character varying(250) COLLATE pg_catalog."default" NOT NULL,
    ff_fb_platform_movie_id character(26) COLLATE pg_catalog."default"          NOT NULL,
    created_timestamp       timestamp with time zone DEFAULT now(),
    last_updated_timestamp  timestamp with time zone DEFAULT now(),
    version_number          integer                  DEFAULT 0,
    created_by              character(26) COLLATE pg_catalog."default",
    last_updated_by         character(26) COLLATE pg_catalog."default",
    CONSTRAINT ff_fb_platform_movies_pkey PRIMARY KEY (ff_fb_platform_movie_id)
);

CREATE TABLE IF NOT EXISTS public.ff_fb_platforms
(
    ff_fb_platform_id      character(26) COLLATE pg_catalog."default" NOT NULL,
    created_timestamp      timestamp with time zone                            DEFAULT now(),
    last_updated_timestamp timestamp with time zone                            DEFAULT now(),
    version_number         integer                                             DEFAULT 0,
    created_by             character(26) COLLATE pg_catalog."default",
    last_updated_by        character(26) COLLATE pg_catalog."default",
    code                   character varying(150) COLLATE pg_catalog."default" DEFAULT 'OMDB'::character varying,
    CONSTRAINT ff_fb_platforms_pkey PRIMARY KEY (ff_fb_platform_id)
);

CREATE TABLE IF NOT EXISTS public.ff_movie_schedules
(
    ff_movie_schedule_id   character(26) COLLATE pg_catalog."default" NOT NULL,
    screen_time            timestamp with time zone                   NOT NULL,
    ff_movie_id            character(26) COLLATE pg_catalog."default" NOT NULL,
    ff_auditorium_id       character(26) COLLATE pg_catalog."default" NOT NULL,
    created_timestamp      timestamp with time zone DEFAULT now(),
    last_updated_timestamp timestamp with time zone DEFAULT now(),
    version_number         integer                  DEFAULT 0,
    created_by             character(26) COLLATE pg_catalog."default",
    last_updated_by        character(26) COLLATE pg_catalog."default",
    price                  numeric(10, 2)           DEFAULT 0,
    CONSTRAINT ff_movie_schedules_pkey PRIMARY KEY (ff_movie_schedule_id)
);

CREATE TABLE IF NOT EXISTS public.ff_movies
(
    ff_movie_id            character(26) COLLATE pg_catalog."default"          NOT NULL,
    title                  character varying(300) COLLATE pg_catalog."default" NOT NULL,
    created_timestamp      timestamp with time zone DEFAULT now(),
    last_updated_timestamp timestamp with time zone DEFAULT now(),
    version_number         integer                  DEFAULT 0,
    created_by             character(26) COLLATE pg_catalog."default",
    last_updated_by        character(26) COLLATE pg_catalog."default",
    CONSTRAINT ff_movies_pkey PRIMARY KEY (ff_movie_id)
);

CREATE TABLE IF NOT EXISTS public.ff_ratings
(
    ff_rating_id           character(26) COLLATE pg_catalog."default"          NOT NULL,
    rating                 smallint                                            NOT NULL,
    comment                text COLLATE pg_catalog."default",
    rating_user            character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ff_movied_id           character(26) COLLATE pg_catalog."default"          NOT NULL,
    created_timestamp      timestamp with time zone DEFAULT now(),
    last_updated_timestamp timestamp with time zone DEFAULT now(),
    version_number         integer                  DEFAULT 0,
    created_by             character(26) COLLATE pg_catalog."default",
    last_updated_by        character(26) COLLATE pg_catalog."default",
    CONSTRAINT ff_ratings_pkey PRIMARY KEY (ff_rating_id)
);

CREATE TABLE IF NOT EXISTS public.ff_theaters
(
    ff_theater_id          character(26) COLLATE pg_catalog."default"          NOT NULL,
    name                   character varying(250) COLLATE pg_catalog."default" NOT NULL,
    created_timestamp      timestamp with time zone DEFAULT now(),
    last_updated_timestamp timestamp with time zone DEFAULT now(),
    version_number         integer                  DEFAULT 0,
    created_by             character(26) COLLATE pg_catalog."default",
    last_updated_by        character(26) COLLATE pg_catalog."default",
    CONSTRAINT ff_theaters_pkey PRIMARY KEY (ff_theater_id)
);

ALTER TABLE IF EXISTS public.ff_auditoriums
    ADD CONSTRAINT fk_theater_1 FOREIGN KEY (ff_theater_id)
        REFERENCES public.ff_theaters (ff_theater_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.ff_fb_platform_movies
    ADD CONSTRAINT fk_fb_plaform_2 FOREIGN KEY (ff_fb_platform_id)
        REFERENCES public.ff_fb_platforms (ff_fb_platform_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.ff_fb_platform_movies
    ADD CONSTRAINT fk_movie_3 FOREIGN KEY (ff_movie_id)
        REFERENCES public.ff_movies (ff_movie_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.ff_movie_schedules
    ADD CONSTRAINT fk_auditorium_1 FOREIGN KEY (ff_auditorium_id)
        REFERENCES public.ff_auditoriums (ff_auditorium) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.ff_movie_schedules
    ADD CONSTRAINT fk_movie_2 FOREIGN KEY (ff_movie_id)
        REFERENCES public.ff_movies (ff_movie_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.ff_ratings
    ADD CONSTRAINT fk_movied_id FOREIGN KEY (ff_movied_id)
        REFERENCES public.ff_movies (ff_movie_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

END;