version: "3.9"
services:
  app:
    image: emilrycombel/er-code-public:1.0.0
    ports:
      - "8080:8080"
    environment:
      platform.database.username: cinemaadmin
      platform.database.password: 123456
      platform.database.url: db:5432
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: ff-cinema
      POSTGRES_USER: cinemaadmin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5455:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
